languageCode: en-us

# To make .html URL's and relative links to avoid baseURL
uglyurls: true
relativeurls: true

theme: massively
publishDir: docs

title: MYTHAXIS MAGAZINE • ISSUE 23

googleanalytics: 'UA-146012578-1'
disqusShortname: ''

taxonomies:
  category: categories
  issue: issues
  tag: tags

disableKinds:
  - taxonomy
  - taxonomyTerm
  - RSS


params:
  posts:
    pageSize: '50'
    featuredPost: true
    paginationPages: 2
    showFirstLast: false

languages:
  en:
    languageName: English

staticDir:
- static
- static-xway

menu:
  main:
    - name: Home
      url: /
      weight: -10
    - name: Editorial
      url: /issue-23/editorial.html
      weight: -9
    - name: Contents
      url: /issue-23/contents.html
      weight: -8
    - name: Archive
      url: /archive.html
      weight: -7
    - name: Submissions
      url: /submissions.html
      weight: -6
    - name: Contact
      url: /about.html
      weight: -5
